const express = require('express')
const router = express.Router()
const userController = require('../controllers/UserController')
const { authMiddleWare, authUserMiddleWare } = require('../middleware/authMiddleware')
router.post('/sign-up', userController.createUser)
// router.post('/sign-up',userController.loginUser)
router.post('/sign-in', userController.loginUser)
router.put('/update-user/:id', authUserMiddleWare, userController.updateUser)
router.delete('/delete-user/:id', authMiddleWare, userController.deleteUser)
// router.get('/getAll', authMiddleWare, userController.getAllUser)
router.get('/getAll', userController.getAllUser)
router.get('/get-details/:id', authUserMiddleWare, userController.getDetailsUser)
router.post('/refresh-token', userController.refreshToken)
router.post('/signout', userController.logoutUser)
router.post('/delete-many', authMiddleWare, userController.deleteManyUser)
// router.get('/getAll',(req,res)=>{
//     return res.status(200).json({data:'HELLO GETALL'})
// })
module.exports = router